# .scrutinizer.yml
build:
    environment:
        php:
            version: 7.0
    tests:
        override:
            -
                command: ./api/run-tests.sh
                coverage:
                    file: ./api/build/logs/clover.xml
                    format: php-clover
