language: php

matrix:
    include:
        - php: 5.6
          env:
            - EXECUTE_COVERAGE=true
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: 7.0

before_script:
    - cd api
    - composer self-update

install:
    - composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
    phpunit -c module/Channel/test/phpunit.xml
