sudo: required
dist: trusty

cache:
  apt: true
  directories:
    - api/vendor
    - $HOME/.composer/cache

language: php

php:
  - 5.6
  - 7.0
# addons:
#   postgresql: "9.4"
services:
  - postgresql
env:
  - MODULE=api
  # - MODULE=web

branches:
  except:
    - legacy
    - experimental

# matrix:
#   allow_failures:
#     - php: 7.0

before_install:
    # temporarily add custom PostgreSQL 9.5 setup commands until available
    - sudo /etc/init.d/postgresql stop
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
    - sudo apt-get update
    - sudo apt-get install postgresql-9.5 postgresql-client-9.5 postgresql-client-common postgresql-common postgresql-contrib-9.5

install:
  # Nothing

before_script:
  - psql --quiet "postgres" -U postgres -f resources/database/init.sql
  - psql --quiet "neap" -U postgres -f resources/database/structure.sql
  - psql --quiet "neap" -U postgres -f resources/database/oauth2.sql
  - psql --quiet "neap" -U postgres -f resources/database/data.sql
  # - psql --quiet "neap" -U postgres -f resources/database/fixtures.sql
  # - psql --quiet "neap" -U postgres -f resources/database/test-fixtures.sql
  - chmod +x $MODULE/run-tests.sh

script:
  - $MODULE/run-tests.sh --travis
