sudo: false

cache:
    apt: true
    directories:
        - api/vendor
        - $HOME/.composer/cache

language: php

php:
    - 5.6
    - 7.0
services:
    - postgresql
addons:
    postgresql: "9.4"

matrix:
    allow_failures:
        - php: 7.0

before_install:
    # - apt-get update -q

install:
    - composer self-update
    - ( cd api ; composer install --no-interaction --ignore-platform-reqs --prefer-source )

before_script:
    - psql "postgres" -U postgres < bootstrap/resources/database/init.sql
    - psql "neap" -U postgres < bootstrap/resources/database/structure.sql
    - psql "neap" -U postgres < bootstrap/resources/database/oauth2.sql
    - psql "neap" -U postgres < bootstrap/resources/database/data.sql
    - cp api/config/autoload/local.php.dist api/config/autoload/local.php
    - cp api/config/autoload/oauth2.local.php.dist api/config/autoload/oauth2.local.php

script:
    - ls api/module/Channel/test/
    - cat api/module/Channel/test/
    - ( cd api/module/Channel/test ; phpunit -c phpunit.xml )
