language: php

php:
    - 5.6
    - 7.0

env:
    - DB=pgsql

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - if [[ "$DB" == "pgsql" ]]; then sudo -u "postgres" psql "postgres" < resources/database/init.sql; fi
    - if [[ "$DB" == "pgsql" ]]; then sudo -u "postgres" psql "neap" < resources/database/structure.sql; fi
    - if [[ "$DB" == "pgsql" ]]; then sudo -u "postgres" psql "neap" < resources/database/oauth2.sql; fi
    - if [[ "$DB" == "pgsql" ]]; then sudo -u "postgres" psql "neap" < resources/database/data.sql; fi
    - cd api
    - composer self-update
    - composer install --no-interaction --ignore-platform-reqs --prefer-source

# install:
#     - composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
    phpunit -c module/Channel/test/phpunit.xml
