sudo: false

cache:
    apt: true
    directories:
        - api/vendor
        - $HOME/.composer/cache

language: php

php:
    - 5.6
    - 7.0
services:
    - postgresql
addons:
    postgresql: "9.4"
env:
    - MODULE=api
    # - MODULE=web

matrix:
    allow_failures:
        - php: 7.0

before_install:
    # Nothing

install:
    # Nothing

before_script:
    - psql "postgres" -U postgres < bootstrap/resources/database/init.sql
    - psql "neap" -U postgres < bootstrap/resources/database/structure.sql
    - psql "neap" -U postgres < bootstrap/resources/database/oauth2.sql
    - psql "neap" -U postgres < bootstrap/resources/database/data.sql

script:
    - ls $MODULE
    - $MODULE/test.sh
