sudo: false

cache:
    apt: true
    directories:
        - api/vendor
        - $HOME/.composer/cache

language: php

php:
    - 5.6
    - 7.0
services:
    - postgresql
addons:
    postgresql: "9.4"

matrix:
    allow_failures:
        - php: 7.0

before_install:
    # - apt-get update -q

install:
    - cd api
    - composer self-update
    - composer install --no-interaction --ignore-platform-reqs --prefer-source

before_script:
    - psql "postgres" -U postgres < ../resources/database/init.sql
    - psql "neap" -U postgres < ../resources/database/structure.sql
    - psql "neap" -U postgres < ../resources/database/oauth2.sql
    - psql "neap" -U postgres < ../resources/database/data.sql
    - cp config/autoload/local.php.dist config/autoload/local.php

script:
    phpunit -c module/Channel/test/phpunit.xml
