language: php
php:
  - 5.6
  - 7.0

env:
  - DB=pgsql

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer install

script:
    phpunit
