language: php
php:
  - 7.0

# Only build pushes to the master branch, PRs, and branches beginning with
# `test-`. This reduces the number of simultaneous Travis runs, which speeds
# turnaround time on review since there is a cap of 5 simultaneous runs.
branches:
  only:
    - develop
    - master
    - release
    - /^test.*$/
