language: php
php:
  - 5.6
  - 7.0

env:
  - DB=pgsql

matrix:
    env: DB=pgsql
    allow_failures:
        - php: 7.0

before_script:
    - cd api
    - composer self-update
    - composer install --no-interaction

script:
    phpunit tests/bootstrap.php
