sudo: false

cache:
    apt: true
    directories:
    - api/vendor

language: php

php:
    - 5.6
    - 7.0
services:
    - postgresql
addons:
    postgresql: "9.4"

matrix:
    allow_failures:
        - php: 7.0

# before_install:
#     - sudo apt-get update
#     - sudo apt-get -y install postgresql postgresql-contrib
#     - sudo /etc/init.d/postgresql stop
#     - sudo /etc/init.d/postgresql start 9.4

before_script:
    - psql "postgres" -U postgres < resources/database/init.sql
    - psql "neap" -U postgres < resources/database/structure.sql
    - psql "neap" -U postgres < resources/database/oauth2.sql
    - psql "neap" -U postgres < resources/database/data.sql
    - cd api
    - composer self-update
    - composer install --no-interaction --ignore-platform-reqs --prefer-source
    - cp config/autoload/local.php.dist config/autoload/local.php

# install:
#     - composer install --no-interaction --ignore-platform-reqs --prefer-source

script:
    phpunit -c module/Channel/test/phpunit.xml
